# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5edf97797cd0371f06bd90f929a937ddcefb4f55953d61a7265bf8451abe146b94e41fcb6ad759bf7034ce8f06e48630bf5ac203671f8a94da84fbed76ab120

test:
  secret_key_base: a011f4c7fd4205754520a1eba0a4ab2f68f059e81192d5c920610e559ad4d3c4f6da991f0a6833da0f4e0d6839d49c5deba5d181fc0eddde51442c77d2c9ec47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
